/* Local design prototype. No network calls, credentials, or hospital operations. */
'use strict';
const paths={
  plus:'M12 5v14M5 12h14',back:'M19 12H5m6-6-6 6 6 6',right:'m9 5 7 7-7 7',down:'m6 9 6 6 6-6',search:'M21 21l-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0',
  calendar:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2M7 14h3m4 0h3m-10 4h3',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
  records:'M8 4H5v18h14V4h-3M9 2h6v4H9zM8 10h8m-8 5h8',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1zM16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  hospital:'M3 21V7h6V3h12v18H3M13 7h4m-2-2v4M13 13h4m-4 4h4M6 11h1m-1 4h1m-1 4h1',check:'m5 12 4 4L19 6',circlecheck:'M22 11v1a10 10 0 1 1-6-9M22 4 12 14l-3-3',user:'M20 21v-2a6 6 0 0 0-6-6h-4a6 6 0 0 0-6 6v2M16 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  shield:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6zM8 12l3 3 5-6',alert:'M12 3 2 21h20L12 3zM12 9v5m0 3v.5',info:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M12 11v6m0-10v.5',
  refresh:'M20 7v5h-5M4 17v-5h5M6 6a8 8 0 0 1 14 6M4 12a8 8 0 0 0 14 6',external:'M14 3h7v7M21 3 10 14M10 3H3v18h18v-7',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 21h6',link:'M10 13a5 5 0 0 0 7 0l4-4a5 5 0 0 0-7-7l-2 2M14 11a5 5 0 0 0-7 0l-4 4a5 5 0 0 0 7 7l2-2',
  wifi:'M2 8a16 16 0 0 1 20 0M5 12a11 11 0 0 1 14 0M9 16a5 5 0 0 1 6 0M12 20h.01',signal:'M4 20v-4m5 4v-8m5 8V8m5 12V4',battery:'M2 6h17v12H2zM22 10v4M5 9h11v6H5z',wallet:'M3 5h17v15H3zM3 5l14-3v3M15 10h7v6h-7z',sliders:'M4 21v-7m0-4V3m8 18v-9m0-4V3m8 18v-4m0-4V3M1 10h6m2 2h6m2 5h6'
};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.info}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,variant='',disabled=false)=>`<button class="btn ${variant}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;
const badge=(s,t='',ic='')=>`<span class="badge ${t}">${ic?icon(ic):''}${s}</span>`;
const note=(h,s,t='')=>`<div class="notice ${t}"><strong>${h}</strong><p>${s}</p></div>`;
const kv=(k,v,long=false)=>`<div class="kv ${long?'long':''}"><dt>${k}</dt><dd>${v}</dd></div>`;
const textAction=(s,a)=>`<button class="text-btn" data-action="${a}">${s}${icon('right')}</button>`;
const head=(title,sub='',back='',step=0)=>`${step?`<div class="step-meta"><span>${step} / 4 · ${['','医院与渠道','就诊条件','执行设置','确认任务'][step]}</span><span>新建挂号任务</span></div><div class="step-track">${[1,2,3,4].map(i=>`<span class="${i<=step?'done':''}"></span>`).join('')}</div>`:''}<header class="page-head">${back?`<button class="icon-btn back" data-action="go:${back}" aria-label="返回">${icon('back')}</button>`:''}<div class="head-copy"><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div></header>`;
const footer=(s,a,disabled=false,secondary='')=>`<div class="footer-actions">${secondary}${button(s,a,'',disabled)}</div>`;
const tabs=(active)=>`<nav class="tabbar" aria-label="主导航">${[['home','任务','calendar'],['records','记录','records'],['settings','设置','settings']].map(([a,s,i])=>`<button data-action="go:${a}" class="${active===a?'active':''}" ${active===a?'aria-current="page"':''}>${icon(i)}${s}</button>`).join('')}</nav>`;
const hospitals=[{id:'people',name:'北京大学人民医院',short:'人民医院',campus:'西直门院区',area:'西城区',dept:'风湿免疫科门诊',channels:['京通','北京114']},{id:'cancer',name:'中国医学科学院肿瘤医院',short:'肿瘤医院',campus:'潘家园院区',area:'朝阳区',dept:'头外门诊',channels:['北京114','京通']},{id:'youan',name:'首都医科大学附属北京佑安医院',short:'北京佑安医院',campus:'本院',area:'丰台区',dept:'肝病中心一科',channels:['医院服务号']}];
const scenes=[['home','任务首页'],['hospitals','选择医院'],['channels','医院与渠道'],['connect','连接平台'],['conditions','就诊条件'],['schedule','医生与排班'],['execution','执行设置'],['confirm','确认任务'],['task','任务详情'],['order','订单与下一步'],['records','挂号记录'],['connections','平台连接'],['settings','设置']];
const state={scene:'home',mode:'target',hospital:'people',channel:'京通',connections:{'京通':true,'北京114':false,'医院服务号':true},patient:'张*',date:'2026-10-03',dept:'风湿免疫科门诊',dayStatus:'available',doctor:null,slot:null,preselect:false,fee:'100',minutes:'30',release:'2026-09-26T08:00',payment:'insurance',ack:false,taskStatus:'waiting',orderStatus:'pending',orderHospital:'youan',orderChannel:'医院服务号',orderDate:'10月03日',search:'',hospitalFilter:'全部',historyFilter:'全部',homeFilter:'全部医院',emptyHome:false,hospitalState:'ready',settingsReady:true,created:false,queryCount:0,expiryKnown:true};
const hospital=()=>hospitals.find(h=>h.id===state.hospital)||hospitals[0];
const context=()=>`<div class="hospital-context"><h3>${esc(hospital().name)}</h3><p>${esc(hospital().campus)} · ${esc(state.channel)} · 就诊人 ${esc(state.patient||'待选择')}</p></div>`;
const orderHospital=()=>hospitals.find(h=>h.id===state.orderHospital)||hospitals[2];
const viewDate=()=>state.date.slice(5).replace('-','月')+'日';
function navigate(scene){state.scene=scene;render();window.scrollTo({top:0,behavior:'instant'});}
function notify(s){const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.style.display='none',3000);}
function modal(title,body,actions){document.querySelector('#dialog-content').innerHTML=`<h3>${title}</h3><p>${body}</p>${actions}`;document.querySelector('#dialog').showModal();}
function resetDependent(){state.patient='';state.doctor=null;state.slot=null;state.preselect=false;state.dayStatus='unqueried';state.ack=false;state.release='';}
function currentGate(){return state.mode==='current'&&state.hospital!=='youan';}
function renderHome(){
  if(state.mode==='current')return `<div class="page">${head('挂号任务','当前能力边界')}${note('北京通用平台接入准备中','已验证官方页面的医院、科室和排班查询；本 App 的独立连接与自动预约尚未完成。')}${button('浏览医院目录示例','go:hospitals','secondary')}<div class="review-only"><strong>UI 评审说明</strong>切换左侧“目标体验”可体验完整流程。该流程使用合成数据，不代表已交付能力。</div></div>${tabs('home')}`;
  const entries=state.created?[{h:hospital(),ch:state.channel,time:'明天 08:00',doctor:state.doctor||'陈医生',phase:'等待放号'}]:[{h:hospitals[0],ch:'京通',time:'明天 08:00',doctor:'陈医生',phase:'等待放号'},{h:hospitals[1],ch:'北京114',time:'完善草稿',doctor:'李医生',phase:'待连接'}];
  return `<div class="page">${head('挂号任务',state.emptyHome?'提前设置，到点自动尝试':state.created?'1 个等待放号 · 1 项需要处理':'1 个等待放号 · 1 个草稿')}${state.emptyHome?`<div class="empty"><div class="empty-icon">${icon('calendar')}</div><h3>安排好下一次就诊</h3><p>选择医院和就诊条件。<br>到放号时间自动尝试，有结果后提醒你。</p>${button('新建第一个任务','go:hospitals')}</div>`:`<button class="attention-banner" data-action="pending-order">${icon('wallet')}<div><strong>有一笔订单等待付款</strong><p>北京佑安医院 · 到官方渠道完成</p></div>${icon('right')}</button><div class="filters"><div class="chip-group"><button class="chip active" data-action="home-active">待办 ${entries.length}</button></div><button class="text-btn" data-action="home-filter">${esc(state.homeFilter)} ${icon('down')}</button></div>${entries.filter(t=>state.homeFilter==='全部医院'||t.h.id==='people').map(t=>`<button class="task-card" data-action="task:${t.h.id}"><div class="between">${badge(t.phase,t.phase==='待连接'?'amber':'',t.phase==='待连接'?'link':'clock')}<span class="when">${t.time}</span></div><h3>${t.h.name}</h3><p class="source">${t.ch} · ${t.h.campus}</p><p class="target">${t.h.dept} · ${t.doctor}</p><p class="visit">${icon('calendar')}10月03日 上午 <span>· 张*</span></p></button>`).join('')}<div class="small-readiness">${icon('shield')}运行准备已检查 · 各医院任务独立执行</div>`}</div>${state.emptyHome?'':`<div class="home-create">${button(icon('plus')+'新建挂号任务','go:hospitals')}</div>`}${tabs('home')}`;
}
function renderHospitals(){
 let list=hospitals.filter(h=>(h.name+h.short).includes(state.search)&&(state.hospitalFilter==='全部'||h.area===state.hospitalFilter));
 return `<div class="page">${head('选择医院','先找到医院，再选择预约渠道','home',1)}<label class="search">${icon('search')}<input id="hospital-search" placeholder="搜索医院名称" aria-label="搜索医院名称" value="${esc(state.search)}"></label><div class="chip-group">${['全部','西城区','朝阳区','丰台区'].map(s=>`<button class="chip ${s===state.hospitalFilter?'active':''}" data-action="filter:${s}">${s}</button>`).join('')}</div>${state.hospitalState==='error'?`<div class="empty"><div class="empty-icon">${icon('wifi')}</div><h3>暂时无法加载医院</h3><p>请检查网络后重试。<br>加载失败不会被当作医院不存在。</p>${button('重新加载','hospital-retry','secondary')}</div>`:`<section class="section"><div class="section-heading"><h3>${state.search?'搜索结果':'医院目录'}</h3><small>北京 · 示例目录</small></div>${list.length?list.map(h=>`<button class="hospital-row" data-action="hospital:${h.id}"><span class="hospital-icon">${icon('hospital')}</span><div class="hospital-copy"><h3>${h.name}</h3><p>${h.area} · ${h.campus}</p>${badge(state.mode==='current'&&h.id!=='youan'?'接入准备中':'可自动挂号',state.mode==='current'&&h.id!=='youan'?'neutral':'')} <small class="muted">${h.channels.join(' / ')}</small></div>${icon('right')}</button>`).join(''):`<div class="empty"><h3>没有匹配的医院</h3><p>试试医院全名，或清除区县筛选。</p>${button('清除筛选','clear-search','secondary')}</div>`}</section>`}<p class="section-description">医院收录与自动挂号能力分别展示，具体以医院、院区和渠道的可用状态为准。</p></div>`;
}
function renderChannels(){return `<div class="page">${head('医院与渠道','','hospitals',1)}<div class="hospital-context"><h3>${hospital().name}</h3><p>${hospital().area} · 普通门诊</p></div><label class="field"><span>就诊院区</span><select id="campus"><option>${hospital().campus}</option></select></label><section class="section"><div class="section-heading"><h3>选择预约渠道</h3></div>${hospital().channels.map(ch=>`<button class="selection-card ${state.channel===ch?'active':''}" data-action="channel:${ch}" aria-pressed="${state.channel===ch}"><div class="between"><span class="title">${ch}</span>${state.channel===ch?icon('circlecheck'):badge(currentGate()?'接入准备中':state.connections[ch]?'已连接':'未连接',state.connections[ch]&&!currentGate()?'':'neutral')}</div><div class="description">${currentGate()?'自动挂号接入准备中':state.connections[ch]?'已连接 · 可核对该渠道就诊人':'继续后完成连接，再核对就诊人'}</div></button>`).join('')}</section>${note('每个渠道单独连接','京通登录不会让北京114自动登录。就诊人和订单也按预约渠道分别核对。')}${currentGate()?`<div class="review-only"><strong>当前能力边界</strong>已观察官方页面查询，独立 App 接入尚未验证。本状态不开放创建自动任务。</div>`:''}</div>${footer(currentGate()?'自动挂号接入准备中':state.connections[state.channel]?'继续 · 核对就诊人':'继续 · 连接'+state.channel,'channel-next',currentGate())}`;}
function renderConnect(){return `<div class="page">${head('连接'+state.channel,'完成连接后，核对可用就诊人','channels',1)}<div class="hospital-context"><h3>${hospital().name}</h3><p>${hospital().campus} · ${state.channel}</p></div><div class="timeline"><div class="timeline-item"><span class="timeline-icon">1</span><div><strong>在官方渠道完成身份验证</strong><small>使用你自己的账号，按官方页面提示操作。</small></div></div><div class="timeline-item"><span class="timeline-icon">2</span><div><strong>回到挂号，校验连接结果</strong><small>只有账号与就诊信息核对成功，才显示已连接。</small></div></div><div class="timeline-item"><span class="timeline-icon">3</span><div><strong>选择本次就诊人</strong><small>登录账号与实际就诊人可能不同。</small></div></div></div>${note('等待完成官方验证','返回后可以再次校验，已保存的任务不会自动恢复。')}${button('打开官方验证入口','official-login','secondary')}</div>${footer('校验连接结果','verify-connection',currentGate())}`;}
function patientRows(){return ['张*','李*'].map((p,i)=>`<button class="selection-card ${state.patient===p?'active':''}" data-action="patient:${p}" aria-pressed="${state.patient===p}"><div class="between"><div class="inline">${icon('user')}<span class="title">${p}</span><small class="muted">${i?'家人':'本人'}</small></div>${state.patient===p?icon('circlecheck'):''}</div><p class="description">${esc(state.channel)}已绑定 · 身份证尾号 ${i?'5678':'1234'}</p></button>`).join('');}
function renderConditions(){return `<div class="page">${head('为谁安排就诊','','channels',2)}${context()}<div class="section-heading"><h3>选择就诊人</h3><small>${esc(state.channel)}的就诊人</small></div>${patientRows()}<label class="field"><span>门诊科室</span><select id="department"><option ${state.dept===hospital().dept?'selected':''}>${hospital().dept}</option><option ${state.dept==='普通内科门诊'?'selected':''}>普通内科门诊</option></select></label>${state.hospital==='youan'?`<label class="field"><span>是否专程来京就医</span><select id="purpose"><option>否</option><option>是</option></select></label>`:''}${note('使用该渠道已绑定的就诊信息','如果缺少就诊人，请先在官方渠道添加，再返回刷新。')}${textAction('刷新就诊人','refresh-patients')}</div>${footer('下一步 · 选择日期和医生','go:schedule',!state.patient)}`;}
const dates=[['2026-10-03','周六','有号'],['2026-10-04','周日','无号'],['2026-10-05','周一','未放号'],['2026-10-06','周二','待查询']];
function renderSchedule(){const available=state.dayStatus==='available',pre=state.preselect;const label={available:'已查询 · 当前有号',none:'已查询 · 当日无号',pending:'已查询 · 尚未放号',error:'读取失败 · 号源状态未知',unqueried:'请查询所选日期的排班'}[state.dayStatus];return `<div class="page">${head('选择就诊时间','','conditions',2)}${context()}<div class="between"><h3>${esc(state.dept)}</h3>${textAction('更换','change-dept')}</div><div class="between date-head"><h3>2026年10月</h3>${textAction('更多日期','more-dates')}</div><div class="date-strip">${dates.map(([d,w,s])=>`<button class="date-tile ${state.date===d?'active':''}" data-action="date:${d}" aria-pressed="${state.date===d}"><small>${w}</small><strong>${Number(d.slice(-2))}</strong><small>${s}</small></button>`).join('')}</div><div class="date-status"><span class="dot"></span>${label}</div>${state.dayStatus==='unqueried'?button('查询当日排班','query','secondary'):''}${state.dayStatus==='error'?note('没有查到可靠的排班信息','网络恢复后重新查询；读取失败不等于当日无号。','red')+button('重新查询','query','secondary'):''}${state.dayStatus==='none'||state.dayStatus==='pending'?`<div class="notice ${state.dayStatus==='pending'?'':'amber'}"><strong>${state.dayStatus==='pending'?'这一天尚未放号':'这一天暂时无号'}</strong><p>${state.dayStatus==='pending'?'医院尚未公布可预约排班。可以预选医生，执行时再次核实目标日排班。':'可以换一天查看，或预选指定医生等待后续号源。预选不会改变当前无号状态。'}</p>${textAction(pre?'收起预选医生':'预选医生','preselect')}</div>`:''}${available||pre?`<section class="section"><div class="section-heading"><h3>${pre?'预选指定医生':'选择医生与时段'}</h3>${badge(pre?'排班待确认':'排班已公布',pre?'amber':'')}</div>${['陈医生','李医生'].map((d,i)=>`<div class="selection-card doctor ${state.doctor===d?'active':''}"><button class="between doctor-select" style="border:0;background:none;padding:0;min-height:48px;width:100%;text-align:left" data-action="doctor:${d}" aria-pressed="${state.doctor===d}"><span><strong class="title">${d}</strong><span class="doctor-detail" style="display:block">${i?'副主任医师':'主任医师'}</span></span>${state.doctor===d?icon('circlecheck'):`<span class="fee">${pre?'费用待公布':'¥'+(i?'50':'100')}</span>`}</button>${pre?`<p class="description">目标日是否出诊、费用和具体时段待确认</p>`:`<div class="slots">${(i?['下午 14:00–15:00']:['上午 08:00–09:00','上午 09:00–10:00']).map(s=>`<button class="slot ${state.doctor===d&&state.slot===s?'active':''}" data-action="slot:${d}|${s}">${s}</button>`).join('')}</div>`}</div>`).join('')}<p class="section-description">${pre?'只尝试指定医生；未匹配到目标日排班时等待至任务截止。':'09:41 查询 · 提交前重新核实排班和费用'}</p></section>`:''}${state.doctor?`<p class="chosen-summary">${icon('check')}${state.doctor} · ${pre?'预选 / 目标日排班待确认':esc(state.slot||'请选择时段')}</p>`:''}</div>${footer('下一步 · 执行设置','go:execution',!state.doctor||(!pre&&!state.slot))}`;}
function renderExecution(){return `<div class="page">${head('设置自动尝试','','schedule',3)}${context()}<section><div class="section-heading"><h3>计划查号时间</h3>${badge(state.release?'医院放号时间已带入':'请填写时间',state.release?'':'amber')}</div><label class="field"><span>北京时间</span><input type="datetime-local" id="release" value="${state.release}" required><small>示例规则：09月26日 08:00 放号。实际以所选医院与日期的规则为准。</small></label></section><section class="section"><h3>最长运行时长</h3><div class="chip-group" style="margin-top:12px">${['15','30','60'].map(s=>`<button class="chip ${state.minutes===s?'active':''}" data-action="minutes:${s}">${s} 分钟${s==='30'?' · 默认':''}</button>`).join('')}${textAction('自定义','custom-minutes')}</div><p class="section-description">到截止时间自动停止查号。付款期限由医院订单另行决定。</p></section><label class="field"><span>单次挂号费用上限（元）</span><input id="fee" type="number" min="1" step="1" value="${state.fee}"><small>提交前重新核对实际费用；费用未知时不提交。</small></label><section class="section"><h3>付款偏好</h3>${[['insurance','优先医保','无法使用时提醒处理，由你决定下一步。'],['self','自费付款','产生有效订单后，由你到官方渠道付款。']].map(([v,t,s])=>`<button class="selection-card ${state.payment===v?'active':''}" data-action="payment:${v}" aria-pressed="${state.payment===v}"><div class="between"><span class="title">${t}</span>${state.payment===v?icon('circlecheck'):''}</div><p class="description">${s}</p></button>`).join('')}</section></div>${footer('下一步 · 核对并启用','go:confirm',!validExecution())}`;}
function validExecution(){return Number(state.fee)>0&&Number(state.minutes)>0&&Number.isInteger(Number(state.minutes))&&Boolean(state.release);}
function readyLine(t,s,ok=true){return `<div class="checkline ${ok?'':'warning'}">${icon(ok?'circlecheck':'alert')}<div>${t}<p>${s}</p></div>${!ok?'<button data-action="resolve-readiness">去设置</button>':''}</div>`;}
function renderConfirm(){return `<div class="page">${head('确认这次安排','','execution',4)}<dl class="keyvalues">${kv('就诊医院',hospital().name+' · '+hospital().campus,true)}${kv('预约渠道',esc(state.channel))}${kv('就诊人',esc(state.patient||'张*'))}${kv('科室 / 医生',esc(state.dept)+' · '+esc(state.doctor||'陈医生'),true)}${kv('就诊日期',viewDate()+' · '+esc(state.slot||'上午 / 排班待确认'))}${kv('计划查号',state.release?state.release.replace('T',' '):'请填写')}${kv('最长尝试',state.minutes+' 分钟')}${kv('费用上限','¥'+esc(state.fee))}${kv('付款偏好',state.payment==='insurance'?'优先医保':'自费付款')}</dl>${state.preselect?note('目标日排班待确认','你预选了医生。只有重新取得与条件匹配的排班和费用后，任务才会提交。','amber'):''}<section class="section"><h3>启用前检查</h3>${readyLine(state.channel+'连接','本次只使用所选渠道的账号和就诊人。')}${readyLine('运行准备',state.settingsReady?'通知与定时设置已检查。':'通知未允许，请完成设置后再启用。',state.settingsReady)}</section><label class="check-box"><input type="checkbox" id="confirm-ack" ${state.ack?'checked':''}><span>我已核对医院、院区和就诊条件；付款需在官方渠道完成。</span></label><p class="section-description">其他医院任务独立执行，成功后不会自动取消其他任务或订单。</p></div>${footer('确认开启自动挂号','enable',!state.ack||!state.settingsReady||currentGate()||!validExecution())}`;}
function renderTask(){let st=state.taskStatus;let titles={waiting:'等待放号',searching:'正在查号',reconciling:'结果待核对',blocked:'暂缓提交',stopped:'任务已停止',expired:'本次未挂到',attention:'连接需要更新'};return `<div class="page">${head('任务详情','','home')}${st==='waiting'||st==='searching'?`<div class="time-hero">${badge(titles[st])}<div class="huge">${st==='waiting'?(state.release.slice(11)||'08:00'):'正在查号'}</div><p>${st==='waiting'?(state.release.slice(5,10).replace('-','月')+'日 · 北京时间'):'尚未发现匹配号源，正在按计划尝试'}</p><p class="hero-rule">${st==='waiting'?'到点自动尝试，最长运行 '+state.minutes+' 分钟':'最近一次查询 09:41:05 · 截止 10:00'}</p></div>`:note(titles[st],{reconciling:'已发送请求，正在核对医院是否生成订单。确认结果前不会重复提交。',blocked:'同一平台账号有一笔提交结果待核对，暂缓本任务提交；其他账号的任务继续。',stopped:'本次自动查号已停止。医院已有订单保持原状态。',expired:'已达到计划截止时间。可查看记录，或复用条件重新安排。',attention:'原渠道连接失效，任务暂停。更新连接后请重新核对再恢复。'}[st],st==='stopped'||st==='expired'?'':'amber')}<section class="section">${context()}<dl class="keyvalues">${kv('就诊人',state.patient||'张*')}${kv('科室 / 医生',state.dept+' · '+(state.doctor||'陈医生'),true)}${kv('就诊安排',viewDate()+' 上午')}${kv('费用上限','¥'+esc(state.fee))}${kv('排班状态',state.preselect?'目标日排班待确认':'目标日排班已确认')}</dl></section><div class="timeline"><div class="timeline-item"><span class="timeline-icon">${icon('check')}</span><div>就诊条件已确认<small>09月25日 09:40 · 任务创建</small></div></div><div class="timeline-item"><span class="timeline-icon">${icon('clock')}</span><div>${titles[st]}<small>${st==='reconciling'?'仅核对本次提交，不发起新预约':'使用任务创建时的医院与渠道'}</small></div></div></div>${st==='reconciling'||st==='blocked'?`${button('核对本次结果','reconcile','secondary')}${textAction('查看原渠道核对步骤','official-order')}`:st==='attention'?button('更新原渠道连接','reconnect','secondary'):st==='stopped'||st==='expired'?button('复用条件新建任务','reuse','secondary'):button('停止本次任务','stop','secondary')}<p class="section-description">停止任务不会取消医院订单。取消或退款请在订单原渠道操作。</p></div>`;}
function renderOrder(){const paid=state.orderStatus==='paid',unknown=state.orderStatus==='unknown';const oh=orderHospital();return `<div class="page">${head('挂号结果','','records')}<div class="order-hero ${paid?'paid':''}">${icon(paid?'circlecheck':'wallet')}<h3>${paid?'挂号已完成':unknown?'付款结果待核对':'已生成订单，待付款'}</h3><p class="deadline">${paid?'医院已确认付款与预约结果':unknown?'已返回 App，正在以医院记录确认付款状态。':state.expiryKnown?'付款截止：今天 10:15<br>请在医院要求的时间内完成付款。':'付款截止时间未返回<br>请立即到官方订单核对。'}</p></div><section class="section"><h3>${oh.name}</h3><p class="section-description">${oh.dept} · 陈医生<br>${state.orderDate} 上午 · 就诊人 张*</p></section><section class="section"><dl class="keyvalues">${kv('订单金额','<span class="money">¥100.00</span>')}${kv('原预约渠道',esc(state.orderChannel))}${kv('订单号','示例 · 09250001')}${kv('医院付款状态',paid?'已付款，已核实':unknown?'待核对':'未付款')}</dl></section>${paid?note('就诊前再核对取号要求','请携带有效身份证件，查看医院订单中的报到地点、时间与取号说明。'):note('回到原渠道完成付款',state.orderChannel==='医院服务号'?'微信 → 北京佑安医院服务号 → 挂号结果查询 → 核对本单。付款后返回这里刷新。':state.orderChannel+' → 预约挂号 → 个人中心 → 预约记录。请核对医院、就诊日期与本单。')}${paid?'':`<p class="order-source">打开官方页面和点击“刷新”都不会直接将订单标记为已付款。</p>`}</div>${footer(paid?'查看官方就诊说明':'到'+state.orderChannel+'查看本单','official-order',false,!paid?button('刷新医院付款结果','refresh-order','secondary'):'')}`;}
function renderRecords(){const rows=[['待付款','北京佑安医院','医院服务号 · 10月03日 上午','pending','amber'],['已完成','北京大学人民医院','京通 · 09月22日 上午','paid',''],['未挂到','中国医学科学院肿瘤医院','北京114 · 09月20日 上午','expired','neutral']].filter(r=>state.historyFilter==='全部'||r[0]===state.historyFilter);return `<div class="page">${head('挂号记录','查看每次安排的结果和下一步')}<div class="chip-group">${['全部','待付款','已完成','未挂到'].map(s=>`<button class="chip ${state.historyFilter===s?'active':''}" data-action="history:${s}">${s}</button>`).join('')}</div><section class="section">${rows.map(([st,h,sub,t,c])=>`<button class="task-card" data-action="record:${t}"><div class="between">${badge(st,c)}<small class="muted">09月25日</small></div><h3>${h}</h3><p class="source">${sub}</p><div class="between"><span class="target">张* · ${h.includes('肿瘤')?'头外门诊':'普通门诊'}</span>${icon('right')}</div></button>`).join('')}</section></div>${tabs('records')}`;}
function renderConnections(){return `<div class="page">${head('平台连接','各渠道的登录与就诊人分别管理','settings')}${[['京通','适用于已接入的北京医院'],['北京114','适用于已接入的北京医院'],['医院服务号','北京佑安医院']].map(([ch,desc])=>`<section class="connection-row"><div class="between"><h3>${ch}</h3>${badge(state.mode==='current'&&ch!=='医院服务号'?'接入准备中':state.connections[ch]?'已连接':'未连接',state.connections[ch]&&!(state.mode==='current'&&ch!=='医院服务号')?'':'neutral')}</div><p>${desc}</p><p>${state.mode==='current'&&ch!=='医院服务号'?'官方渠道登录不代表本 App 已连接':state.connections[ch]?'就诊人 张*、李* · 09:40 校验':'需要单独连接，其他平台登录不会同步'}</p>${textAction(state.connections[ch]?'查看与管理':'连接'+ch,'manage:'+ch)}</section>`).join('')}${note('连接更新与任务恢复分开','新增或更新连接不会替换已启用任务的身份。已有提交结果未明确时，先用相同身份核对原订单。')}</div>`;}
function renderSettings(){return `<div class="page">${head('设置','管理连接与自动执行准备')}<section><button class="settings-row" data-action="go:connections">${icon('link')}<div><strong>平台连接</strong><small>京通、北京114与医院服务号</small></div>${icon('right')}</button><button class="settings-row" data-action="readiness">${icon('shield')}<div><strong>运行准备</strong><small>${state.settingsReady?'通知、精确定时与后台设置已检查':'1 项需要处理 · 通知未允许'}</small></div>${state.settingsReady?badge('已检查'):badge('待处理','amber')}</button><button class="settings-row" data-action="defaults">${icon('sliders')}<div><strong>新任务默认值</strong><small>尝试 30 分钟 · 优先医保</small></div>${icon('right')}</button></section><section class="section"><h3>数据留在本机</h3><p class="section-description">连接资料、就诊信息与任务加密保存。<br>默认值变化仅影响新任务。</p></section><section class="section"><h3>后台运行说明</h3><p class="section-description">请保持手机开机且网络可用。权限已开启仍可能受系统省电影响，可在运行准备中检查设置。</p></section></div>${tabs('settings')}`;}
const renderers={home:renderHome,hospitals:renderHospitals,channels:renderChannels,connect:renderConnect,conditions:renderConditions,schedule:renderSchedule,execution:renderExecution,confirm:renderConfirm,task:renderTask,order:renderOrder,records:renderRecords,connections:renderConnections,settings:renderSettings};
function renderTools(){let options=[];if(state.scene==='home')options=[['空任务首页','empty-home'],['多医院任务','populated-home']];if(state.scene==='hospitals')options=[['读取失败','catalog-error'],['正常目录','catalog-ok']];if(state.scene==='schedule')options=[['有号','status:available'],['当日无号','status:none'],['尚未放号','status:pending'],['读取失败','status:error'],['未查询','status:unqueried']];if(state.scene==='task')options=[['等待放号','phase:waiting'],['正在查号','phase:searching'],['结果待核对','phase:reconciling'],['同账号暂缓','phase:blocked'],['连接失效','phase:attention'],['已停止','phase:stopped'],['未挂到','phase:expired']];if(state.scene==='order')options=[['待付款','order:pending'],['期限未知','unknown-expiry'],['结果待核对','order:unknown'],['医院确认完成','order:paid']];if(state.scene==='confirm')options=[['准备已完成','ready'],['通知未允许','not-ready']];document.querySelector('#scenario-tools').innerHTML=options.length?`<span class="tools-label">评审情境 · 不属于产品界面</span>${options.map(([s,a])=>`<button data-action="${a}">${s}</button>`).join('')}`:'';}
function render(){document.querySelector('#app').innerHTML=renderers[state.scene]();document.querySelector('#scene-name').textContent=scenes.find(s=>s[0]===state.scene)?.[1]||'';document.querySelector('#scene-nav').innerHTML=scenes.map(([a,s],i)=>`<button class="${state.scene===a?'selected':''}" data-action="scene:${a}"><span>${String(i+1).padStart(2,'0')}</span>${s}</button>`).join('');document.querySelector('#mode').value=state.mode;document.querySelector('#mode-help').textContent=state.mode==='target'?'本页是 UI 原型。人物、日期、费用、订单均为示例，不连接医院，也不会发起挂号。':'当前只验证了官方页面查询。114 / 京通独立接入、认证与预约未完成，对应自动任务入口保持关闭。';renderTools();}
function setSceneDefaults(a){if(a==='connect'){state.channel='北京114';state.connections['北京114']=false;}if(['schedule','execution','confirm'].includes(a)){state.patient='张*';state.release='2026-09-26T08:00';if(a!=='schedule'){state.doctor='陈医生';state.slot='上午 08:00–09:00';}}}
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b||b.disabled)return;let a=b.dataset.action,[k,...parts]=a.split(':'),v=parts.join(':');
 if(k==='go')return navigate(v);if(k==='scene'){setSceneDefaults(v);return navigate(v)}
 if(k==='hospital'){state.hospital=v;state.channel=hospital().channels[0];resetDependent();state.dept=hospital().dept;return navigate('channels')}
 if(k==='channel'){if(state.channel!==v){state.channel=v;resetDependent()}return render()}
 if(k==='patient'){state.patient=v;state.doctor=null;state.slot=null;state.ack=false;return render()}
 if(k==='filter'){state.hospitalFilter=v;return render()}
 if(k==='history'){state.historyFilter=v;return render()}
 if(k==='date'){state.date=v;state.doctor=null;state.slot=null;state.preselect=false;state.ack=false;state.dayStatus='unqueried';return render()}
 if(k==='doctor'){state.doctor=v;state.slot=state.preselect?'上午':null;state.ack=false;return render()}
 if(k==='slot'){[state.doctor,state.slot]=v.split('|');state.ack=false;return render()}
 if(k==='payment'){state.payment=v;state.ack=false;return render()}
 if(k==='minutes'){state.minutes=v;state.ack=false;return render()}
 if(k==='phase'){state.taskStatus=v;return render()}
 if(k==='status'){state.dayStatus=v;state.doctor=null;state.slot=null;state.preselect=false;return render()}
 if(k==='order'){state.orderStatus=v;state.expiryKnown=true;return render()}
 if(k==='task'){state.hospital=v;state.channel=hospital().channels[0];state.dept=hospital().dept;if(v==='cancer'&&!state.connections[state.channel])return navigate('channels');state.taskStatus='waiting';return navigate('task')}
 if(k==='record'){if(v==='expired'){state.taskStatus='expired';return navigate('task')}state.orderStatus=v;state.orderHospital=v==='paid'?'people':'youan';state.orderChannel=v==='paid'?'京通':'医院服务号';state.orderDate=v==='paid'?'09月22日':'10月03日';return navigate('order')}
 if(k==='manage'){state.channel=v;if(state.mode==='current'&&v!=='医院服务号')return modal('接入准备中','本 App 尚未完成此渠道的独立认证；官方渠道登录状态不等于 App 已连接。',button('知道了','close'));return modal('管理'+v,(state.connections[v]?'已连接。可重新校验，或移除本机连接。':'此渠道尚未连接。')+'<br>旧任务和医院订单不会因管理连接而被取消。',button('重新校验连接','manage-verify')+button('移除本机连接','remove-connection','secondary')+button('关闭','close','secondary'))}
 switch(a){
 case 'close':document.querySelector('#dialog').close();break;
 case 'channel-next':if(currentGate())return;navigate(state.connections[state.channel]?'conditions':'connect');break;
 case 'official-login':modal('官方验证入口','原型仅演示交接。正式入口及认证回传方式须验证后启用，这里不会打开微信或获取登录信息。',button('返回设计','close'));break;
 case 'verify-connection':if(currentGate())return;state.connections[state.channel]=true;state.patient='';navigate('conditions');notify('示例校验通过，请核对就诊人');break;
 case 'query':state.queryCount++;state.dayStatus={'2026-10-03':'available','2026-10-04':'none','2026-10-05':'pending','2026-10-06':'error'}[state.date]||'pending';state.doctor=null;state.slot=null;state.preselect=false;state.release='2026-09-26T08:00';render();break;
 case 'preselect':state.preselect=!state.preselect;state.doctor=null;state.slot=null;render();break;
 case 'change-dept':state.doctor=null;state.slot=null;state.preselect=false;state.dayStatus='unqueried';navigate('conditions');break;
 case 'more-dates':modal('选择就诊日期','<label class="field"><span>就诊日期</span><input id="more-date" type="date" value="'+state.date+'"></label>',button('使用这个日期','use-date')+button('返回','close','secondary'));break;
 case 'use-date':state.date=document.querySelector('#more-date').value||state.date;state.dayStatus='unqueried';state.doctor=null;state.slot=null;state.preselect=false;document.querySelector('#dialog').close();render();break;
 case 'custom-minutes':modal('最长运行时长','<label class="field"><span>分钟</span><input id="custom-duration" type="number" min="1" step="1" value="'+state.minutes+'"></label>只影响本次任务，不改变订单付款期限。',button('保存时长','save-duration')+button('返回','close','secondary'));break;
 case 'save-duration':{let m=Number(document.querySelector('#custom-duration').value);if(!Number.isInteger(m)||m<1){notify('请输入正整数分钟');return}state.minutes=String(m);document.querySelector('#dialog').close();render();break}
 case 'enable':if(!state.ack||currentGate()||!validExecution()||!state.settingsReady)return;state.created=true;state.taskStatus='waiting';navigate('task');notify('示例任务已启用，不连接医院');break;
 case 'stop':modal('停止本次自动挂号？','只停止当前任务的后续查号。已有医院订单不会取消，其他医院任务继续执行。',button('停止本次任务','stop-confirm','danger')+button('继续等待','close','secondary'));break;
 case 'stop-confirm':state.taskStatus='stopped';document.querySelector('#dialog').close();render();break;
 case 'reconcile':notify('示例：医院结果仍待核对，不会重复提交');break;
 case 'reconnect':navigate('connect');break;
 case 'reuse':state.created=false;state.ack=false;state.doctor=null;state.slot=null;state.dayStatus='unqueried';navigate('conditions');break;
 case 'official-order':{let ch=state.scene==='task'?state.channel:state.orderChannel;let h=state.scene==='task'?hospital():orderHospital();modal('到'+ch+'核对',h.name+'<br>'+ch+' → 预约挂号 → 个人中心 / 挂号结果查询。核对就诊人、日期、金额与订单号。<br>这是原型演示，不打开真实订单。',button('返回挂号','close'));break;}
 case 'refresh-order':state.orderStatus='unknown';render();notify('示例：医院结果尚未确认，保持待核对');break;
 case 'pending-order':state.orderStatus='pending';state.orderHospital='youan';state.orderChannel='医院服务号';state.orderDate='10月03日';navigate('order');break;
 case 'refresh-patients':notify('示例就诊人已刷新，仅属于 '+state.channel);break;
 case 'hospital-retry':case 'catalog-ok':state.hospitalState='ready';render();break;
 case 'catalog-error':state.hospitalState='error';render();break;
 case 'clear-search':state.search='';state.hospitalFilter='全部';render();break;
 case 'home-filter':state.homeFilter=state.homeFilter==='全部医院'?'人民医院':'全部医院';render();break;
 case 'home-active':notify('正在显示等待放号与待完善的任务');break;
 case 'empty-home':state.emptyHome=true;render();break;
 case 'populated-home':state.emptyHome=false;render();break;
 case 'ready':state.settingsReady=true;render();break;
 case 'not-ready':state.settingsReady=false;render();break;
 case 'unknown-expiry':state.orderStatus='pending';state.expiryKnown=false;render();break;
 case 'readiness':case 'resolve-readiness':modal('运行准备','通知：'+(state.settingsReady?'已允许':'未允许')+'<br>精确定时：已检查<br>后台运行：已检查<br><br>系统设置入口在 Android 实现时按真机适配，原型仅演示恢复。',button('模拟完成设置','readiness-ok')+button('关闭','close','secondary'));break;
 case 'readiness-ok':state.settingsReady=true;document.querySelector('#dialog').close();render();break;
 case 'defaults':modal('新任务默认值','默认尝试 30 分钟，优先医保。修改仅影响之后新建的任务；已启用任务保持原设置。',button('知道了','close'));break;
 case 'manage-verify':state.connections[state.channel]=true;document.querySelector('#dialog').close();render();notify('示例连接已校验，已有任务不会自动恢复');break;
 case 'remove-connection':modal('移除 '+state.channel+' 本机连接？','存在待核对提交时，应保留核对所需的连接。本示例没有关联的未决提交。移除不会删除任务或取消医院订单。',button('移除这个连接','remove-confirm','danger')+button('保留连接','close','secondary'));break;
 case 'remove-confirm':state.connections[state.channel]=false;document.querySelector('#dialog').close();render();break;
 }
});
document.addEventListener('input',e=>{let t=e.target;if(t.id==='hospital-search'){state.search=t.value;let pos=t.selectionStart;render();let n=document.querySelector('#hospital-search');n.focus();n.setSelectionRange(pos,pos)}if(t.id==='fee'||t.id==='release'){state[t.id]=t.value;state.ack=false;let next=document.querySelector('[data-action="go:confirm"]');if(next)next.disabled=!validExecution()}});
document.addEventListener('change',e=>{let t=e.target;if(t.id==='mode'){state.mode=t.value;state.ack=false;render()}if(t.id==='department'){state.dept=t.value;state.doctor=null;state.slot=null;state.preselect=false;state.dayStatus='unqueried';state.ack=false}if(t.id==='confirm-ack'){state.ack=t.checked;render()}});
const params=new URLSearchParams(location.search);if(params.has('full'))document.body.classList.add('full');if(params.has('embed'))document.body.classList.add('embed');if(params.has('scene')&&renderers[params.get('scene')]){state.scene=params.get('scene');setSceneDefaults(state.scene)}if(params.get('mode')==='current')state.mode='current';if(params.has('status')){let s=params.get('status');if(state.scene==='task')state.taskStatus=s;if(state.scene==='schedule'){state.dayStatus=s;state.date=({none:'2026-10-04',pending:'2026-10-05',error:'2026-10-06',unqueried:'2026-10-06'})[s]||'2026-10-03';}if(state.scene==='order')state.orderStatus=s}if(params.get('preselect')==='true'){state.preselect=true;state.doctor='陈医生';state.slot='上午'}if(params.get('empty')==='true')state.emptyHome=true;
document.querySelector('#system-icons').innerHTML=icon('signal')+icon('wifi')+icon('battery');document.querySelector('#spec-link').href='../../docs/design/ui/2026-09-25-v0.2-ui-design.md';render();
